/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;
import java.lang.ArithmeticException;
import static java.lang.Math.sqrt;
/**
 *
 * @author Dell
 */
public class CalculatorGui extends javax.swing.JFrame {
    double number;
    double result = 0;
    int count = 0;
    int countDecimal = 0;
    int firstNumber = 0;
    boolean CEFlag = false;
    boolean performedAction = false;
    String operation;
    /**
     * Creates new form CalculatorGui
     */
    public CalculatorGui() {  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton18.setText("√");
        jButton18.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton18.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton17.setText("CE");
        jButton17.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton17.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton15.setText("%");
        jButton15.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton15.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton16.setText("C");
        jButton16.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton16.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("x²");
        jButton7.setBorder(null);
        jButton7.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton7.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setText("√");
        jButton8.setBorder(null);
        jButton8.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton8.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("%");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton9.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("1/x");
        jButton10.setBorder(null);
        jButton10.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton10.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.setBorder(null);
        jTextField1.setSelectionColor(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setBorder(null);
        jTextField3.setSelectionColor(new java.awt.Color(204, 204, 204));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText(" ±");
        jButton13.setBorder(null);
        jButton13.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton13.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton14.setText("=");
        jButton14.setBorder(null);
        jButton14.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton14.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("0");
        jButton12.setBorder(null);
        jButton12.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton12.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText(".");
        jButton11.setBorder(null);
        jButton11.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton11.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculator/Capture2.PNG"))); // NOI18N
        jButton19.setBorder(null);
        jButton19.setIconTextGap(0);
        jButton19.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton19.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton20.setText("C");
        jButton20.setBorder(null);
        jButton20.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton20.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton21.setText("CE");
        jButton21.setBorder(null);
        jButton21.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton21.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setText("÷");
        jButton22.setBorder(null);
        jButton22.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton22.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton23.setText("7");
        jButton23.setBorder(null);
        jButton23.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton23.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton24.setText("×");
        jButton24.setBorder(null);
        jButton24.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton24.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton25.setText("9");
        jButton25.setBorder(null);
        jButton25.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton25.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(255, 255, 255));
        jButton26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton26.setText("8");
        jButton26.setBorder(null);
        jButton26.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton26.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(255, 255, 255));
        jButton27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton27.setText("4");
        jButton27.setBorder(null);
        jButton27.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton27.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton28.setText("−");
        jButton28.setBorder(null);
        jButton28.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton28.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setBackground(new java.awt.Color(255, 255, 255));
        jButton29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton29.setText("6");
        jButton29.setBorder(null);
        jButton29.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton29.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setBackground(new java.awt.Color(255, 255, 255));
        jButton30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton30.setText("5");
        jButton30.setBorder(null);
        jButton30.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton30.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setBackground(new java.awt.Color(255, 255, 255));
        jButton31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton31.setText("1");
        jButton31.setBorder(null);
        jButton31.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton31.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton32.setText(" +  ");
        jButton32.setBorder(null);
        jButton32.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton32.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setBackground(new java.awt.Color(255, 255, 255));
        jButton33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton33.setText("3");
        jButton33.setBorder(null);
        jButton33.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton33.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(255, 255, 255));
        jButton34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton34.setText("2");
        jButton34.setBorder(null);
        jButton34.setMaximumSize(new java.awt.Dimension(50, 25));
        jButton34.setMinimumSize(new java.awt.Dimension(50, 25));
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber = firstNumber + 1;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton34.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton33.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
      try{
            if(operation != "%" && operation != "=" )
            {
                number =  Double.parseDouble(jTextField1.getText());
                if(count == 0){
                    result = number;
                    count++;
                }
                if(operation == "x"){
                     result = result * number;
                }else if(operation == "-"){
                     result = result - number;
                }else if(operation == "/"){
                     result = result/ number;
                }else if(operation == "+")
                {
                    result = result + number;
                }
                jTextField3.setText(jTextField3.getText() + jTextField1.getText() + " + "); 
                jTextField1.setText("");
                performedAction = true;
                countDecimal = 0;
                operation = "+";
            }else if(operation.indexOf('=') != -1)
            {
                result = Double.parseDouble(jTextField1.getText());
                jTextField3.setText("");
                jTextField3.setText(jTextField1.getText() + " + "); 
                jTextField1.setText("");
                countDecimal = 0;
                firstNumber++;
                count++;
                operation = "+";
            }
            else{
                number = Double.parseDouble(jTextField1.getText());
                jTextField3.setText(jTextField1.getText() + " + "); 
                performedAction = true;
                jTextField1.setText("" + result);
                countDecimal = 0;
                operation = "+";
            }
        }catch(Exception err){
            jTextField1.setText("");
            String check = jTextField3.getText();
            int len = check.length();
            if(len > 0){
                if(check.charAt(len-1) != '+'){
                        //System.out.println(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText() +  jTextField1.getText() + " +"); 
                }else{
                     jTextField3.setText(jTextField3.getText());
                }
            }else{
                jTextField3.setText("");
            }
        }    
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton31.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            firstNumber++;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton30.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton29.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton29ActionPerformed

    public double codeAddition(){
         try{
            if(operation != "%" && operation != "=" )
            {
                if(operation == "x"){
                     result = result * number;
                }else if(operation == "-"){
                     result = result - number;
                }else if(operation == "/"){
                     result = result/ number;
                }
                number =  Double.parseDouble(jTextField1.getText());
                result = result + number;
                System.out.println("add: " + result);
                jTextField3.setText(jTextField3.getText() + jTextField1.getText() + " + "); 
                jTextField1.setText(""+result);
                performedAction = true;
                countDecimal = 0;
                operation = "+";
                //count++;
            }else if(operation.indexOf('=') != -1)
            {
                
                //result = result;
                number = Double.parseDouble(jTextField1.getText());
                result = number;
                jTextField3.setText("");
                jTextField3.setText(jTextField1.getText() + " + "); 
                jTextField1.setText("");
                countDecimal = 0;
                firstNumber++;
                operation = "+";
            }
            else{
                
                number = Double.parseDouble(jTextField1.getText());
                jTextField3.setText(jTextField1.getText() + " + "); 
                performedAction = true;
                jTextField1.setText("" + result);
                countDecimal = 0;
                operation = "+";
            }
        }catch(Exception err){
            jTextField1.setText("");
            String check = jTextField3.getText();
            int len = check.length();
            if(len > 0){
                if(check.charAt(len-1) != '+'){
                        //System.out.println(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText() +  jTextField1.getText() + " +"); 
                }else{
                     jTextField3.setText(jTextField3.getText());
                }
            }else{
                jTextField3.setText("");
            }
        }
        
        return result;
    }
    public double codeSubtraction(){
        try{
           if(operation != "%" && operation != "=")
           {
               number =  Double.parseDouble(jTextField1.getText());
                if(operation == "x"){
                     result = result * number;
                     jTextField1.setText("" + result);
                }else if(operation == "+"){
                     codeAddition();
                }else if(operation == "/"){
                     result = result/ number;
                     jTextField1.setText("" + result);
                }
                number =  Double.parseDouble(jTextField1.getText());
             
                if(count != 0){
                    result = result - number;
                }
                else{
                    result = number;
                    count++;
                }
                System.out.println("Modified:" + result);
                jTextField3.setText(jTextField3.getText() + jTextField1.getText() + " - "); 
                jTextField1.setText(""+result);
                performedAction = true;
                countDecimal = 0;
                operation = "-";
           }else if(operation.indexOf('=') != -1)
            {
                operation = "-";
                //result = result;
                number = Double.parseDouble(jTextField1.getText());
                result = number;
                jTextField3.setText("");
                jTextField3.setText(jTextField1.getText() + " - "); 
                jTextField1.setText("");
                countDecimal = 0;
                firstNumber++;
            }
           else{
                operation = "-";
                number = Double.parseDouble(jTextField1.getText());
                jTextField3.setText(jTextField1.getText() + " - "); 
                performedAction = true;
                jTextField1.setText("" + result);
                countDecimal = 0;
            }
        }catch(Exception err){
            jTextField1.setText("");
            String check = jTextField3.getText();
            int len = check.length();
            if(len > 0){
                if(check.charAt(len-1) != '-'){
                        jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText() +  jTextField1.getText() + " -"); 
                }else{
                     jTextField3.setText(jTextField3.getText());
                }
            }else{
                jTextField3.setText("");
            }
        }
        return result;
    }
    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
       try{
           if(operation != "%" && operation != "=")
           {
               number =  Double.parseDouble(jTextField1.getText());
                if(count == 0){
                    result = number;
                    count++;
                }
                if(operation == "x"){
                     result = result * number;
                }else if(operation == "-"){
                     result = result - number;
                }else if(operation == "/"){
                     result = result/ number;
                }else if(operation == "+")
                {
                    result = result + number;
                }
                jTextField3.setText(jTextField3.getText() + jTextField1.getText() + " - "); 
                jTextField1.setText("");
                performedAction = true;
                countDecimal = 0;
                operation = "-";
           }else if(operation.indexOf('=') != -1)
            {
                result = Double.parseDouble(jTextField1.getText());
                jTextField3.setText("");
                jTextField3.setText(jTextField1.getText() + " - "); 
                jTextField1.setText("");
                countDecimal = 0;
                firstNumber++;
                count++;
                operation = "-";
            }
            else{
                number = Double.parseDouble(jTextField1.getText());
                jTextField3.setText(jTextField1.getText() + " - "); 
                performedAction = true;
                jTextField1.setText("" + result);
                countDecimal = 0;
                operation = "-";
            }
        }catch(Exception err){
            jTextField1.setText("");
            String check = jTextField3.getText();
            int len = check.length();
            if(len > 0){
                if(check.charAt(len-1) != '-'){
                        jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText() +  jTextField1.getText() + " -"); 
                }else{
                     jTextField3.setText(jTextField3.getText());
                }
            }else{
                jTextField3.setText("");
            }
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction= false;
        }
        String data = jTextField1.getText() + jButton27.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton26.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
            countDecimal=0;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton25.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        try{
            if(operation != "%" && operation != "=")
            {
                number =  Double.parseDouble(jTextField1.getText());
                System.out.println("Number: " + number);
                if(count == 0){
                    result = number;
                    count++;
                }
                if(operation == "x"){
                     result = result * number;
                }else if(operation == "-"){
                     result = result - number;
                }else if(operation == "/"){
                     result = result/ number;
                }else if(operation == "+")
                {
                    result = result + number;
                }
                jTextField3.setText(jTextField3.getText() + jTextField1.getText() + " x "); 
                jTextField1.setText("");
                performedAction = true;
                countDecimal = 0;
                operation = "x";
            }else if(operation.indexOf('=') != -1)
            {
                result = Double.parseDouble(jTextField1.getText());
                jTextField3.setText("");
                jTextField3.setText(jTextField1.getText() + " x "); 
                jTextField1.setText("");
                countDecimal = 0;
                firstNumber++;
                count++;
                operation = "x";
            }
            else{
                number = Double.parseDouble(jTextField1.getText());
                jTextField3.setText(jTextField1.getText() + " x "); 
                performedAction = true;
                jTextField1.setText("" + result);
                countDecimal = 0;
                operation = "x";
            }
        }catch(Exception err){
          
            String check = jTextField3.getText();
            int len = check.length();
            if(len > 0){
                if(check.charAt(len-1) != 'x'){
                        jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText() +  jTextField1.getText() + " x"); 
                }else{
                     jTextField3.setText(jTextField3.getText());
                     jTextField1.setText("");
                }
            }else{
                jTextField1.setText("");
                jTextField3.setText("");
            }
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
        }if(CEFlag == true || performedAction==true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton23.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        try{
            if(operation != "%" && operation != "=")
            {
                countDecimal = 0;
                number =  Double.parseDouble(jTextField1.getText());
                if(count == 0){
                    result = number;
                    count++;
                }else{
                     if(operation == "x"){
                        result = result * number;
                    }else if(operation == "-"){
                        result = result - number;
                    }else if(operation == "+"){
                        result = result + number;
                    }else if(operation == "/"){
                        result = result / number;
                    }
                    // result = result/number;
                   if(Double.isInfinite(result)){
                       throw new ArithmeticException();
                   }
                }
                operation = "/";
                //jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-1));
                jTextField3.setText(jTextField3.getText() +  jTextField1.getText() + " / "); 
                jTextField1.setText("");
            }else if(operation.indexOf('=') != -1)
            {
               result = Double.parseDouble(jTextField1.getText());
                jTextField3.setText("");
                jTextField3.setText(jTextField1.getText() + " / "); 
                jTextField1.setText("");
                countDecimal = 0;
                firstNumber++;
                count++;
                operation = "/";
            }
            else{
                number = Double.parseDouble(jTextField1.getText());
                jTextField3.setText(jTextField1.getText() + " / "); 
                performedAction = true;
                jTextField1.setText("" + result);
                countDecimal = 0;
                operation = "/";
            }
        }catch(ArithmeticException err){
            jTextField1.setText("Cannot Divide by Zero");
            jTextField3.setText("");
        }catch(Exception err){
            
            jTextField1.setText("");
            String check = jTextField3.getText();
            int len = check.length();
            if(len > 0){
                if(check.charAt(len-1) != '/'){
                        //System.out.println(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText().substring(0,jTextField3.getText().length()-2));
                        jTextField3.setText(jTextField3.getText() +  jTextField1.getText() + " /"); 
                }else{
                     jTextField3.setText(jTextField3.getText());
                }
            }else{
                jTextField3.setText("");
            }
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        CEFlag = true;
        countDecimal = 0;
        number = 0;
        //firstNumber = 0;
        if(operation == "="){
            jTextField3.setText("");
        }        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(""+ 0);
        firstNumber = 0;
        if(jTextField3.getText() != ""){
            number = 0;
            result = 0;
            //secondnumber = 0;
            jTextField3.setText("");
        }
        result = 0;
        number = 0;
        countDecimal = 0;
        count = 0;
        CEFlag = false;
        performedAction = false;
        jTextField3.setText("");
        operation = "";
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().length() > 0 && operation != "=")
        {
            String check = jTextField1.getText();
            //check if the backspaced letter is decimal then decrease count of decimal
            int len = check.length();
            len--;
            if(check.charAt(len) == '.'){
                countDecimal = 0;
            }
            jTextField1.setText(jTextField1.getText().substring(0,jTextField1.getText().length()-1));
        }
        else if(jTextField1.getText().length() > 0 && operation == "="){
            jTextField3.setText("");
            result = 0;
            number = 0;
            operation = "=";
            countDecimal = 0;
            count = 0;
            firstNumber = 0;
            CEFlag = false;
            performedAction = false;
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText() != "" && countDecimal == 0 && jTextField1.getText().indexOf(".") == -1)
        {
            String data = jTextField1.getText() + jButton11.getText();
            jTextField1.setText(data);
            countDecimal++;
            firstNumber=1;
        }
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(firstNumber == 0){
            jTextField1.setText("");
            jTextField3.setText("");
            firstNumber++;
        }
        if(CEFlag == true || performedAction == true){
            jTextField1.setText("");
            CEFlag = false;
            performedAction = false;
        }
        String data = jTextField1.getText() + jButton12.getText();
        jTextField1.setText(data);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try{
            count = 0;
            countDecimal = 0;
            firstNumber = 0;
            number = Double.parseDouble(jTextField1.getText());
            if(operation == "+"){
                result = result + number;
                jTextField1.setText("" + result);
                jTextField3.setText(jTextField3.getText() + number);
            }else if(operation == "x"){
                result = result * number;
                jTextField1.setText("" + result);
                jTextField3.setText(jTextField3.getText() + number);
            }else if(operation == "-"){
                result = result - number;
                jTextField1.setText("" + result);
                jTextField3.setText(jTextField3.getText() + number);
            }else if(operation == "/"){
                try{
                    result = result / number;
                    jTextField1.setText("" + result);
                    jTextField3.setText(jTextField3.getText() + number);
                }catch(ArithmeticException e){
                    jTextField1.setText("Divide By Zero Error");
                }
            }
            //jTextField3.setText("");
            result = 0;
            number = 0;
            operation = "=";
            countDecimal = 0;
            count = 0;
            CEFlag = false;
            performedAction = false;
        }catch(Exception err){
            jTextField1.setText("");
            jTextField3.setText("");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{
            String data = String.valueOf(jTextField1.getText());
            double val = Double.parseDouble(data);
            val = val * -1; //if positive then negative if negative then positive
            jTextField1.setText(String.valueOf(val));  
        }catch(Exception err){
            jTextField1.setText("");
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
             double val =  Double.parseDouble(jTextField1.getText());
             double answer = 1/val;
             if(val!= 0){
                jTextField1.setText(" " + answer);
                countDecimal = 0;
             }
             else{
                 throw new ArithmeticException();
             }
        }catch(ArithmeticException e){
             jTextField1.setText("Cannot Divide by Zero");
             jTextField2.setText("");
        }catch(Exception e){
             jTextField1.setText("");
             jTextField2.setText("");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{
            if(count != 0)
            {
                double val =  Double.parseDouble(jTextField1.getText());
                double ans = val * 0.01;
                if(result != 0){
                    if(operation == "+"){
                        ans = result + (result * ans);
                    }
                    else if(operation == "-"){
                        ans = result -(result * ans);
                    }else if(operation == "/"){
                        ans = result /  ans;
                    }else if(operation == "x"){
                        ans =  result * ans;
                    }
                }
                jTextField3.setText(result + operation + jTextField1.getText() + "%");
                jTextField1.setText(""+ ans);
                result = ans;
                //jTextField3.setText(jTextField3.getText() + val);
                countDecimal = 0;
                //firstNumber = 0;
                count++;
                operation = "%";
            }else{
              double val =  Double.parseDouble(jTextField1.getText());
              double ans = val * 0.01;
               jTextField3.setText(jTextField1.getText() + "%");
                jTextField1.setText(""+ ans);
                //jTextField3.setText(jTextField3.getText() + val);
                countDecimal = 0;
                firstNumber = 0;
                System.out.println("here: "+ result);
            }
        }catch(Exception err){
            jTextField1.setText("");
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            number = Double.parseDouble(jTextField1.getText());
            double ans = sqrt(number);
            //jTextField3.setText(jTextField3.getText() + jTextField1.getText() + " + "); 
            jTextField1.setText(""+ans);
            countDecimal = 0;
        }catch(Exception err){
            jTextField1.setText("");
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       try{
            number = Double.parseDouble(jTextField1.getText());
            double ans = number * number;
            //jTextField3.setText(jTextField3.getText() + jTextField1.getText() + " + "); 
            jTextField1.setText(""+ans);
            countDecimal = 0;
       }catch(Exception err){
            jTextField1.setText("");
            jTextField2.setText("");
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
